# Generated by Django 5.0.6 on 2026-05-18 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')], default=1)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_paid', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('fraud_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'db_table': 'referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_referrals', models.IntegerField(default=0)),
                ('level_1_count', models.IntegerField(default=0)),
                ('level_2_count', models.IntegerField(default=0)),
                ('total_commissions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('level_1_commissions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('level_2_commissions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active_referrals', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Stats',
                'verbose_name_plural': 'Referral Stats',
                'db_table': 'referral_stats',
            },
        ),
    ]
