# Generated by Django 5.0.6 on 2026-05-18 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fraud_type', models.CharField(choices=[('self_referral', 'Self Referral'), ('duplicate_ip', 'Duplicate IP'), ('suspicious_activity', 'Suspicious Activity'), ('multiple_accounts', 'Multiple Accounts'), ('payment_fraud', 'Payment Fraud'), ('withdrawal_fraud', 'Withdrawal Fraud')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fraud Log',
                'verbose_name_plural': 'Fraud Logs',
                'db_table': 'fraud_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'db_table': 'suspicious_ips',
            },
        ),
    ]
